### ISSUE TITLE
TypeError: error setting argument 2 - writePointer: Buffer instance expected as third argument

### ISSUE THREAD

**Issue by blancell** [node-ffi-libraries/node-ffi-library-libusb-v1.0.23#3] opened 2022-03-03 07:15 UTC
const library = await load();  
const headerLoader = library.headers["./include/libusb-1.0/libusb.h"];
  const header = await headerLoader();

  var context = header.types['libusb_contextPointer'];
  var devs = header.types['libusb_devicePointer'];
  var  res = await header.functions.libusb_init(null);

  try {
    let cnt = header.functions.libusb_get_device_list(null, devs);
  } catch (e) {
    console.info("e:"+e);
  }

Hi,  have a exception(TypeError: error setting argument 2 - writePointer: Buffer instance expected as third argument) when run the test code.

**Comment by joelpurra** [comment] 2022-03-03 08:05
@blancell: your code is not allocating memory for the requires types using `ref-napi`, which would give you a `Buffer`, only pointing to the type metadata.  (Note the `-napi` suffix in `ref-napi`; this modern library version is required even though the linked tutorial links to the old `ref` package.)

- https://github.com/node-ffi/node-ffi/wiki/Node-FFI-Tutorial
- https://github.com/node-ffi-napi
- https://github.com/node-ffi-napi/ref-napi

It's easiest if you first write C code, compile and test it fully, then "translate" it to javascript with FFI. Language translation example for `libuvc`:

- https://github.com/joelpurra/node-libuvc
- https://github.com/joelpurra/node-libuvc/blob/develop/examples/stream-disk/
- https://github.com/joelpurra/node-libuvc/tree/develop/examples/reference-implementation/stream-disk

This reported issue is not a bug in `node-ffi-library-libusb-v1.0.23`, so will close it. For usage questions I recommend StackOverflow.

- https://stackoverflow.com/questions/tagged/node-ffi

**Closed as completed by joelpurra** 2022-03-03 08:05 UTC
